import Head from "next/head";
import styles from "@/styles/connect_wallet.module.css";
import Footer from "@/components/Footer/footer.js";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>DeFaS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.bodyContainer}>
        <div className={styles.container}>
          <img className={styles.logo} src="./logo.png" />
          <h1 className={styles.heading1}>DeFaS</h1>
          <p className={styles.bodyText1}>
            DeFaS is a revolutionary fantasy game that offers a unique
            possibility to have fun and win exclusive prize from your knowledge
            at the same time. We ensure that you get most of fantasy sport.
          </p>
          <div>
            <button className={styles.button}>Connect</button>
            <Link href="/display_games">
              <button className={styles.button}>Play Now</button>
            </Link>
          </div>
        </div>
      </div>

      <div className={styles.footer}>
        <Footer />
      </div>
    </>
  );
}
