import Head from "next/head";
import Match from "@/components/Match/match";
import Create from "@/components/Create/create";
import Footer from "@/components/Footer/footer";
import styles from "@/styles/create_contest.module.css";
import Link from "next/link";
import { useState } from "react";

export default function Home({ data }) {
  const [active, setActive] = useState(data[0]);

  return (
    <>
      <Head>
        <title>DeFaS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/view_profile">
        <img className={styles.menu} src="./menu.png" />
      </Link>
      <div className={styles.bodyContainer}>
        <div className={styles.section1}>
          <div className={styles.subsection1}>
            <img className={styles.logo} src="./logo.png" />
            <h1 className={styles.mainHeading}>DeFaS</h1>
          </div>

          <div className={styles.subsection2}>
            <h2>Upcoming Matches</h2>
            <div className={styles.matchList}>
              {data.map((match, i) => (
                <Match
                  key={match.id}
                  format={match.format}
                  startDate={match.startDate}
                  team1={match.team1}
                  team2={match.team2}
                  onclick={() => {
                    setActive(match);
                  }}
                />
              ))}
            </div>
          </div>
        </div>
        <div className={styles.section2}>
          <Create match={active} />
        </div>
      </div>
      <div className={styles.footer}>
        <Footer />
      </div>
    </>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch("https://defas-llc.vercel.app/api/see_matches");
  const data = await res.json();
  //Pass data to the page via props
  return { props: { data } };
}
