import Head from "next/head";

import Team from "@/components/Team/team";
import Player from "@/components/Player/player";
import PickedTeam from "@/components/PickedTeam/pickedTeam";
import Footer from "@/components/Footer/footer";
import Link from "next/link";
import styles from "@/styles/make_team.module.css";
import { useState } from "react";

export default function Home({ data }) {
  const match = JSON.parse(data);

  const [fantasy, setFantasy] = useState([]);

  function selectPlayer(e) {
    if (fantasy.length < 11) {
      let player = {};
      player["id"] = e.target.attributes.playerid.value;
      player["name"] = e.target.attributes.playername.value;
      let newFantasy = [...fantasy, player];
      setFantasy(newFantasy);
    }
  }

  const handleSubmit = async () => {
    const user = "xyz";
    let contestant = { contestant_id: user, team: fantasy };
    match["contestants"].push(contestant);
    await fetch("http://localhost:3000/api/contest", {
      method: "POST",
      body: JSON.stringify(match),
    });
    console.log(match);
  };

  return (
    <>
      <Head>
        <title>DeFaS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/view_profile">
        <img className={styles.menu} src="../menu.png" />
      </Link>

      <div className={styles.bodyContainer}>
        <div className={styles.section1}>
          <div className={styles.subsection1}>
            <img className={styles.logo} src="../logo.png" />
            <h1 className={styles.heading1}>
              Make Picks to Achieve Objective Stats
            </h1>

            <h2 className={styles.bodyText2}>
              Make Picks to Achieve Objective Stats
            </h2>
          </div>
          <div className={styles.subsection2}>
            <div className={styles.card1}>
              <h3 className={styles.heading2}>Select Your Team</h3>
              <div className={styles.teams}>
                <Team
                  name={match.team1}
                  squad={JSON.stringify(match.squad1)}
                  selectPlayer={(e) => {
                    selectPlayer(e);
                  }}
                />
                <Team
                  name={match.team2}
                  squad={JSON.stringify(match.squad2)}
                  selectPlayer={(e) => {
                    selectPlayer(e);
                  }}
                />
              </div>
            </div>
            <div className={styles.card2}>
              <Player />
            </div>
          </div>
          <div className={styles.footer}>
            <Footer />
          </div>
        </div>

        <div className={styles.section2}>
          <PickedTeam team={fantasy} onsubmit={handleSubmit} />
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const match = context.query;

  // Fetch data from external API
  const squad1 = await fetch(
    `http://localhost:3000/api/get_team/?match_id=${match.id}&team_id=${match.team1Id}`
  );

  const squad2 = await fetch(
    `http://localhost:3000/api/get_team/?match_id=${match.id}&team_id=${match.team2Id}`
  );

  match["squad1"] = await squad1.json();

  match["squad2"] = await squad2.json();

  match["contestants"] = [];

  const data = JSON.stringify(match);

  //const data = await res.json();
  //Pass data to the page via props
  return { props: { data } };
}
