import Head from "next/head";
import Listing from "@/components/Listing/listing";
import styles from "@/styles/see_contest.module.css";
import Footer from "@/components/Footer/footer";
import ParticipantTeam from "@/components/ParticipantTeam/participantTeam";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>DeFaS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/view_profile">
        <img className={styles.menu} src="./menu.png" />
      </Link>

      <div className={styles.bodyContainer}>
        <div className={styles.section1}>
          <div className={styles.subsection1}>
            <img className={styles.logo} src="./logo.png" />
            <h1 className={styles.mainHeading}>India Vs Pak</h1>
          </div>

          <div className={styles.subsection2}>
            <h2>Leaderboard</h2>
            <div className={styles.leaderboard}>
              <Listing />
              <Listing />
              <Listing />
              <Listing />
              <Listing />
              <Listing />
              <Listing />
            </div>
          </div>

          <div className={styles.footer}>
            <Footer />
          </div>
        </div>

        <div className={styles.section2}>
          <ParticipantTeam />
        </div>
      </div>
    </>
  );
}
