import Head from "next/head";
import Contest from "@/components/Contest/contest";
import Profile from "@/components/Profile/profile";
import Footer from "@/components/Footer/footer";
import styles from "@/styles/view_profile.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>DeFaS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/view_profile">
        <img className={styles.menu} src="./menu.png" />
      </Link>

      <div className={styles.bodyContainer}>
        <div className={styles.section1}>
          <div className={styles.subsection1}>
            <img className={styles.logo} src="./logo.png" />
            <h1 className={styles.mainHeading}>DeFaS</h1>
          </div>

          <div className={styles.subsection2}>
            <h2>Your Contest</h2>
            <div className={styles.contestList}>
              <Contest />
              <Contest />
              <Contest />
              <Contest />
              <Contest />
              <Contest />
              <Contest />
              <Contest />
              <Contest />
              <Contest />
              <Contest />
              <Contest />
            </div>
          </div>
        </div>
        <div className={styles.section2}>
          <Profile />
        </div>
      </div>

      <div className={styles.footer}>
        <Footer />
      </div>
    </>
  );
}
